name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update data from GitHUb
        run: sh update_from_github.sh

      - name: Update data from Hub API
        run: sh update_from_hubapi.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "github/**/.* hubapi/**/.*"
          commit_message: Update data
