name: Update data from GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update data from GitHub
        run: sh update_from_github.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "**/*.json"
          commit_message: Update data from GitHub
