name: Update server usage

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python -m pip install requests

      - name: Update server usage
        run: python update_server_usage.py

      - name: Pull Remote Changes
        run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "hubapi/server_usage.json"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: Update server usage
